# Generated by Django 2.2.15 on 2020-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一标识，编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('intro', models.CharField(max_length=1000, verbose_name='介绍')),
                ('is_host', models.BooleanField(default=True, verbose_name='是否热门')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'db_table': 'tb_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='老师编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('birth', models.DateTimeField(null=True, verbose_name='生日')),
                ('intro', models.CharField(max_length=1000, verbose_name='自我介绍')),
                ('photo', models.ImageField(max_length=255, upload_to='', verbose_name='照片')),
                ('good_count', models.IntegerField(db_column='goodcount', default=0, verbose_name='好评数')),
                ('bad_count', models.IntegerField(db_column='badcount', default=0, verbose_name='差评数')),
            ],
            options={
                'verbose_name': '学科老师信息',
                'verbose_name_plural': '学科老师信息',
                'db_table': 'tb_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('tel', models.CharField(max_length=12, verbose_name='电话号码')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_visit', models.DateTimeField(null=True, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'tb_user',
            },
        ),
    ]
