# Generated by Django 2.2.15 on 2020-08-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='昵称')),
                ('age', models.IntegerField(blank=True, max_length=2, null=True, verbose_name='年龄')),
            ],
            options={
                'db_table': 'person_info',
            },
        ),
    ]
