# Generated by Django 3.1 on 2020-08-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookIntro',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='图书编号')),
                ('book_name', models.CharField(max_length=100, verbose_name='图书名称')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书信息表',
                'db_table': 'tb_book_intro',
            },
        ),
    ]
